-- ============================================================================
-- SYSTEM TEMPLATES - Omnex Display Hub
-- Profesyonel ESL/Tablet Sablonlari
-- Hedef: 10.1" Dikey ESL Tablet (800x1280)
-- Fabric.js v7 Uyumlu JSON Formati
-- ============================================================================

-- Onceki sistem sablonlarini temizle (varsa)
DELETE FROM templates WHERE scope = 'system' AND company_id IS NULL;

-- ============================================================================
-- SABLON 1: MANAV - DIKEY (Media Ust, Urun Alt)
-- Taze meyve-sebze icin premium tasarim
-- HAL Kunye destegi, tum dinamik alanlar
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-manav-vertical-001',
    NULL,
    'system',
    'Manav Premium - Dikey (Media Ust)',
    'Taze meyve-sebze icin profesyonel tasarim. Ust bolum medya (gorsel/video), alt bolum urun bilgileri. HAL Kunye QR kodu dahil.',
    'label',
    'fresh_produce',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'split-vertical',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 576,
                "fill": "#f0fdf4",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "media"
            },
            {
                "type": "image",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 576,
                "scaleX": 1,
                "scaleY": 1,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 0,
                "top": 576,
                "width": 800,
                "height": 704,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "product"
            },
            {
                "type": "rect",
                "left": 20,
                "top": 596,
                "width": 760,
                "height": 660,
                "fill": "#f8fafc",
                "rx": 16,
                "ry": 16,
                "stroke": "#e2e8f0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 50,
                "top": 620,
                "text": "{{product_name}}",
                "fontSize": 42,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 700,
                "textAlign": "left"
            },
            {
                "type": "i-text",
                "left": 50,
                "top": 680,
                "text": "{{origin}} • {{production_type}}",
                "fontSize": 22,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{origin}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 50,
                "top": 730,
                "width": 700,
                "height": 180,
                "fill": "#ecfdf5",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 760,
                "text": "{{current_price}}",
                "fontSize": 72,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 350,
                "top": 780,
                "text": "TL",
                "fontSize": 36,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 845,
                "text": "/{{unit}}",
                "fontSize": 28,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 500,
                "top": 760,
                "text": "{{previous_price}} TL",
                "fontSize": 28,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#9ca3af",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 620,
                "top": 810,
                "width": 110,
                "height": 50,
                "fill": "#f97316",
                "rx": 25,
                "ry": 25,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 635,
                "top": 820,
                "text": "%{{discount_percent}}",
                "fontSize": 24,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 50,
                "top": 930,
                "width": 700,
                "height": 60,
                "fill": "#fef3c7",
                "rx": 8,
                "ry": 8,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 945,
                "text": "{{campaign_text}}",
                "fontSize": 24,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#92400e",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 50,
                "top": 1010,
                "width": 540,
                "height": 220,
                "fill": "#f1f5f9",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1030,
                "text": "HAL KUNYE BILGILERI",
                "fontSize": 16,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#475569",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1060,
                "text": "Uretici: {{hal.uretici_adi}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.uretici_adi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1090,
                "text": "Urun: {{hal.malin_adi}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.malin_adi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1120,
                "text": "Cins: {{hal.malin_cinsi}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.malin_cinsi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1150,
                "text": "Uretim Yeri: {{hal.uretim_yeri}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.uretim_yeri}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 70,
                "top": 1180,
                "text": "Bildirim: {{hal.ilk_bildirim_tarihi}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.ilk_bildirim_tarihi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 610,
                "top": 1010,
                "width": 140,
                "height": 170,
                "fill": "#ffffff",
                "rx": 8,
                "ry": 8,
                "stroke": "#e2e8f0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 625,
                "top": 1025,
                "width": 110,
                "height": 110,
                "customType": "qrcode",
                "dynamicField": "{{kunye_no}}",
                "qrValue": "{{kunye_no}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 630,
                "top": 1145,
                "text": "Tarimsal",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "textAlign": "center",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 625,
                "top": 1160,
                "text": "Izlenebilirlik",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "textAlign": "center",
                "selectable": false,
                "evented": false
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- SABLON 2: MANAV - VIDEO USTUNDE (Video Ust, Gorsel+Urun Alt)
-- Video odakli tasarim, alt kisim ikiye bolunmus
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-manav-video-top-001',
    NULL,
    'system',
    'Manav Video - Ust Bolum Video',
    'Video icerigi ust bolumde, alt bolum ikiye ayrilmis: sol taraf urun gorseli, sag taraf urun bilgileri ve fiyat.',
    'label',
    'fresh_produce',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'top-one-bottom-two',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 500,
                "fill": "#0f172a",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "video"
            },
            {
                "type": "group",
                "left": 300,
                "top": 180,
                "width": 200,
                "height": 140,
                "customType": "dynamic-video",
                "dynamicField": "{{video_url}}",
                "isVideoPlaceholder": true,
                "selectable": true,
                "evented": true,
                "objects": [
                    {
                        "type": "rect",
                        "left": -100,
                        "top": -70,
                        "width": 200,
                        "height": 140,
                        "fill": "#1e293b",
                        "rx": 12,
                        "ry": 12
                    },
                    {
                        "type": "circle",
                        "left": -30,
                        "top": -30,
                        "radius": 30,
                        "fill": "#22c55e",
                        "opacity": 0.9
                    },
                    {
                        "type": "polygon",
                        "left": -15,
                        "top": -18,
                        "points": [
                            {"x": 0, "y": 0},
                            {"x": 30, "y": 18},
                            {"x": 0, "y": 36}
                        ],
                        "fill": "#ffffff"
                    }
                ]
            },
            {
                "type": "i-text",
                "left": 250,
                "top": 420,
                "text": "Video Icerigi",
                "fontSize": 28,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#94a3b8",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 0,
                "top": 500,
                "width": 350,
                "height": 780,
                "fill": "#f0fdf4",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "image"
            },
            {
                "type": "image",
                "left": 25,
                "top": 520,
                "width": 300,
                "height": 400,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 25,
                "top": 940,
                "width": 300,
                "height": 150,
                "fill": "#dcfce7",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 50,
                "top": 970,
                "width": 90,
                "height": 90,
                "customType": "qrcode",
                "dynamicField": "{{kunye_no}}",
                "qrValue": "{{kunye_no}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 160,
                "top": 980,
                "text": "HAL Kunye",
                "fontSize": 16,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 160,
                "top": 1010,
                "text": "{{hal.uretici_adi}}",
                "fontSize": 14,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.uretici_adi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 160,
                "top": 1035,
                "text": "{{hal.uretim_yeri}}",
                "fontSize": 14,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{hal.uretim_yeri}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 350,
                "top": 500,
                "width": 450,
                "height": 780,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "details"
            },
            {
                "type": "i-text",
                "left": 380,
                "top": 530,
                "text": "{{category}}",
                "fontSize": 18,
                "fontWeight": "500",
                "fontFamily": "Inter, sans-serif",
                "fill": "#22c55e",
                "dynamicField": "{{category}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 380,
                "top": 560,
                "text": "{{product_name}}",
                "fontSize": 36,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#0f172a",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 400
            },
            {
                "type": "i-text",
                "left": 380,
                "top": 630,
                "text": "{{origin}} • {{production_type}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{origin}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "line",
                "left": 380,
                "top": 680,
                "x1": 0,
                "y1": 0,
                "x2": 380,
                "y2": 0,
                "stroke": "#e2e8f0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 380,
                "top": 700,
                "width": 380,
                "height": 200,
                "fill": "#fef2f2",
                "rx": 16,
                "ry": 16,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 410,
                "top": 730,
                "text": "{{current_price}}",
                "fontSize": 80,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 620,
                "top": 750,
                "text": "TL/{{unit}}",
                "fontSize": 28,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 410,
                "top": 830,
                "text": "Eski: {{previous_price}} TL",
                "fontSize": 22,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#9ca3af",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 650,
                "top": 820,
                "width": 100,
                "height": 50,
                "fill": "#22c55e",
                "rx": 25,
                "ry": 25,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 665,
                "top": 832,
                "text": "%{{discount_percent}}",
                "fontSize": 22,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 380,
                "top": 920,
                "width": 380,
                "height": 55,
                "fill": "#fef3c7",
                "rx": 10,
                "ry": 10,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 932,
                "text": "{{campaign_text}}",
                "fontSize": 22,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#92400e",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 380,
                "top": 995,
                "width": 380,
                "height": 260,
                "fill": "#f8fafc",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1015,
                "text": "URUN DETAYLARI",
                "fontSize": 14,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#475569",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1050,
                "text": "Barkod: {{barcode}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1080,
                "text": "SKU: {{sku}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{sku}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1110,
                "text": "Raf: {{shelf_location}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{shelf_location}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1140,
                "text": "Agirlik: {{weight}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{weight}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1170,
                "text": "Stok: {{stock}} adet",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{stock}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 1200,
                "text": "Fiyat Guncelleme: {{price_updated_at}}",
                "fontSize": 14,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#94a3b8",
                "dynamicField": "{{price_updated_at}}",
                "selectable": true,
                "evented": true
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- SABLON 3: ET-BALIK - PREMIUM DIKEY
-- Kirmizi/mavi tonlarda profesyonel tasarim
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-meat-fish-001',
    NULL,
    'system',
    'Et & Balik Premium - Dikey',
    'Et, tavuk ve balik urunleri icin profesyonel tasarim. Kirmizi ve mavi tema secenekleri. Taze gosterge ve kalite rozetleri.',
    'label',
    'meat_fish',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'split-vertical',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 550,
                "fill": "#fef2f2",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "media"
            },
            {
                "type": "image",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 550,
                "scaleX": 1,
                "scaleY": 1,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 20,
                "top": 20,
                "width": 130,
                "height": 45,
                "fill": "#dc2626",
                "rx": 22,
                "ry": 22,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 45,
                "top": 30,
                "text": "TAZE",
                "fontSize": 22,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 0,
                "top": 550,
                "width": 800,
                "height": 730,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "product"
            },
            {
                "type": "rect",
                "left": 0,
                "top": 550,
                "width": 800,
                "height": 8,
                "fill": "#dc2626",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 25,
                "top": 580,
                "width": 750,
                "height": 680,
                "fill": "#fafafa",
                "rx": 20,
                "ry": 20,
                "stroke": "#f0f0f0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 605,
                "text": "{{category}}",
                "fontSize": 20,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{category}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 640,
                "text": "{{product_name}}",
                "fontSize": 44,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#1f2937",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 690
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 705,
                "text": "{{origin}} • {{production_type}}",
                "fontSize": 20,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{origin}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 755,
                "width": 690,
                "height": 200,
                "fill": "#ffffff",
                "rx": 16,
                "ry": 16,
                "stroke": "#fee2e2",
                "strokeWidth": 2,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 785,
                "text": "{{current_price}}",
                "fontSize": 85,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 810,
                "text": "TL",
                "fontSize": 40,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 885,
                "text": "/{{unit}}",
                "fontSize": 26,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 520,
                "top": 780,
                "width": 200,
                "height": 80,
                "fill": "#fef2f2",
                "rx": 10,
                "ry": 10,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 545,
                "top": 790,
                "text": "{{previous_price}} TL",
                "fontSize": 22,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#9ca3af",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 555,
                "top": 825,
                "text": "%{{discount_percent}} INDIRIM",
                "fontSize": 18,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#dc2626",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 975,
                "width": 690,
                "height": 60,
                "fill": "#fef3c7",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 990,
                "text": "{{campaign_text}}",
                "fontSize": 24,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#92400e",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 1055,
                "width": 500,
                "height": 180,
                "fill": "#f9fafb",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 75,
                "top": 1075,
                "text": "URUN BILGILERI",
                "fontSize": 14,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4b5563",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 75,
                "top": 1105,
                "text": "Barkod: {{barcode}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 75,
                "top": 1135,
                "text": "SKU: {{sku}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{sku}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 75,
                "top": 1165,
                "text": "Raf: {{shelf_location}} | Agirlik: {{weight}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{shelf_location}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 75,
                "top": 1195,
                "text": "Stok: {{stock}} adet",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#6b7280",
                "dynamicField": "{{stock}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 575,
                "top": 1055,
                "width": 170,
                "height": 180,
                "fill": "#ffffff",
                "rx": 12,
                "ry": 12,
                "stroke": "#e5e7eb",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 595,
                "top": 1070,
                "width": 130,
                "height": 130,
                "customType": "barcode",
                "dynamicField": "{{barcode}}",
                "barcodeValue": "{{barcode}}",
                "barcodeFormat": "EAN13",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 610,
                "top": 1210,
                "text": "{{barcode}}",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "monospace",
                "fill": "#6b7280",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- SABLON 4: SUT URUNLERI - BEYAZ TEMALI
-- Minimalist beyaz tema, sut ve sut urunleri icin
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-dairy-001',
    NULL,
    'system',
    'Sut Urunleri - Beyaz Tema',
    'Sut, peynir, yogurt gibi sut urunleri icin minimalist beyaz temali tasarim. Temiz ve profesyonel gorunum.',
    'label',
    'dairy',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'split-vertical',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 520,
                "fill": "#f0f9ff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "media"
            },
            {
                "type": "image",
                "left": 50,
                "top": 30,
                "width": 700,
                "height": 460,
                "scaleX": 1,
                "scaleY": 1,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 0,
                "top": 520,
                "width": 800,
                "height": 760,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "product"
            },
            {
                "type": "rect",
                "left": 0,
                "top": 520,
                "width": 800,
                "height": 6,
                "fill": "#3b82f6",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 30,
                "top": 550,
                "width": 740,
                "height": 700,
                "fill": "#fafafa",
                "rx": 20,
                "ry": 20,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 60,
                "top": 575,
                "text": "{{brand}}",
                "fontSize": 18,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#3b82f6",
                "dynamicField": "{{brand}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 60,
                "top": 605,
                "text": "{{product_name}}",
                "fontSize": 40,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#1e3a5f",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 680
            },
            {
                "type": "i-text",
                "left": 60,
                "top": 665,
                "text": "{{category}} • {{subcategory}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{category}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 60,
                "top": 700,
                "text": "{{weight}} | {{origin}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#94a3b8",
                "dynamicField": "{{weight}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 60,
                "top": 750,
                "width": 680,
                "height": 180,
                "fill": "#eff6ff",
                "rx": 16,
                "ry": 16,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 95,
                "top": 780,
                "text": "{{current_price}}",
                "fontSize": 80,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#1e40af",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 380,
                "top": 800,
                "text": "TL",
                "fontSize": 36,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#1e40af",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 95,
                "top": 870,
                "text": "/{{unit}}",
                "fontSize": 24,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 500,
                "top": 770,
                "width": 210,
                "height": 90,
                "fill": "#ffffff",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 525,
                "top": 782,
                "text": "{{previous_price}} TL",
                "fontSize": 20,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#9ca3af",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 535,
                "top": 815,
                "text": "%{{discount_percent}} INDIRIM",
                "fontSize": 18,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#22c55e",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 60,
                "top": 950,
                "width": 680,
                "height": 55,
                "fill": "#f0fdf4",
                "rx": 10,
                "ry": 10,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 90,
                "top": 965,
                "text": "{{campaign_text}}",
                "fontSize": 22,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 60,
                "top": 1025,
                "width": 420,
                "height": 200,
                "fill": "#f8fafc",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1045,
                "text": "URUN DETAYLARI",
                "fontSize": 14,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#475569",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1080,
                "text": "Barkod: {{barcode}}",
                "fontSize": 15,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1110,
                "text": "SKU: {{sku}}",
                "fontSize": 15,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{sku}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1140,
                "text": "Raf Konumu: {{shelf_location}}",
                "fontSize": 15,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{shelf_location}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1170,
                "text": "Stok: {{stock}} adet",
                "fontSize": 15,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#64748b",
                "dynamicField": "{{stock}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 1200,
                "text": "Guncelleme: {{price_updated_at}}",
                "fontSize": 13,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#94a3b8",
                "dynamicField": "{{price_updated_at}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 500,
                "top": 1025,
                "width": 240,
                "height": 200,
                "fill": "#ffffff",
                "rx": 12,
                "ry": 12,
                "stroke": "#e2e8f0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 545,
                "top": 1050,
                "width": 150,
                "height": 150,
                "customType": "barcode",
                "dynamicField": "{{barcode}}",
                "barcodeValue": "{{barcode}}",
                "barcodeFormat": "EAN13",
                "selectable": true,
                "evented": true
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- SABLON 5: TEMEL GIDA - KOMPAKT TASARIM
-- Makarna, bakliyat, konserve gibi temel gidalar icin
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-staples-001',
    NULL,
    'system',
    'Temel Gida - Kompakt Tasarim',
    'Makarna, pirinc, bakliyat, konserve gibi temel gida urunleri icin kompakt ve fonksiyonel tasarim.',
    'label',
    'staples',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'split-vertical',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 480,
                "fill": "#fef7ee",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "media"
            },
            {
                "type": "image",
                "left": 100,
                "top": 20,
                "width": 600,
                "height": 440,
                "scaleX": 1,
                "scaleY": 1,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 0,
                "top": 480,
                "width": 800,
                "height": 800,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "product"
            },
            {
                "type": "rect",
                "left": 0,
                "top": 480,
                "width": 800,
                "height": 8,
                "fill": "#f97316",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 25,
                "top": 508,
                "width": 750,
                "height": 750,
                "fill": "#fffbf5",
                "rx": 20,
                "ry": 20,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 530,
                "text": "{{brand}}",
                "fontSize": 20,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ea580c",
                "dynamicField": "{{brand}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 560,
                "text": "{{product_name}}",
                "fontSize": 38,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#292524",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 690
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 620,
                "text": "{{category}} | {{weight}}",
                "fontSize": 18,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{category}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 665,
                "width": 690,
                "height": 190,
                "fill": "#fff7ed",
                "rx": 16,
                "ry": 16,
                "stroke": "#fed7aa",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 90,
                "top": 700,
                "text": "{{current_price}}",
                "fontSize": 85,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#c2410c",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 400,
                "top": 720,
                "text": "TL",
                "fontSize": 38,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#c2410c",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 90,
                "top": 800,
                "text": "/{{unit}}",
                "fontSize": 24,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 500,
                "top": 690,
                "width": 220,
                "height": 100,
                "fill": "#ffffff",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 530,
                "top": 705,
                "text": "{{previous_price}} TL",
                "fontSize": 22,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#a8a29e",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 520,
                "top": 740,
                "width": 180,
                "height": 42,
                "fill": "#16a34a",
                "rx": 21,
                "ry": 21,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 550,
                "top": 750,
                "text": "%{{discount_percent}}",
                "fontSize": 22,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 875,
                "width": 690,
                "height": 60,
                "fill": "#dcfce7",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 890,
                "text": "{{campaign_text}}",
                "fontSize": 24,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 955,
                "width": 380,
                "height": 280,
                "fill": "#f5f5f4",
                "rx": 16,
                "ry": 16,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 975,
                "text": "URUN BILGILERI",
                "fontSize": 14,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#57534e",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1010,
                "text": "Barkod: {{barcode}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1045,
                "text": "SKU: {{sku}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{sku}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1080,
                "text": "Raf: {{shelf_location}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{shelf_location}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1115,
                "text": "Tedarikci: {{supplier_code}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{supplier_code}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1150,
                "text": "Stok: {{stock}} adet",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{stock}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1185,
                "text": "Mensei: {{origin}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#78716c",
                "dynamicField": "{{origin}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 455,
                "top": 955,
                "width": 290,
                "height": 280,
                "fill": "#ffffff",
                "rx": 16,
                "ry": 16,
                "stroke": "#e7e5e4",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 490,
                "top": 975,
                "width": 220,
                "height": 180,
                "customType": "barcode",
                "dynamicField": "{{barcode}}",
                "barcodeValue": "{{barcode}}",
                "barcodeFormat": "EAN13",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 515,
                "top": 1170,
                "text": "{{barcode}}",
                "fontSize": 14,
                "fontWeight": "normal",
                "fontFamily": "monospace",
                "fill": "#78716c",
                "dynamicField": "{{barcode}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 500,
                "top": 1200,
                "text": "Son Guncelleme: {{price_updated_at}}",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#a8a29e",
                "dynamicField": "{{price_updated_at}}",
                "selectable": true,
                "evented": true
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- SABLON 6: MANAV ORGANIK - YESIL TEMA
-- Organik ve naturel urunler icin ozel tasarim
-- ============================================================================
INSERT INTO templates (
    id, company_id, scope, name, description, type, category,
    width, height, orientation, target_device_type, grid_layout,
    design_data, status, created_at
) VALUES (
    'sys-tpl-organic-001',
    NULL,
    'system',
    'Organik Urunler - Yesil Premium',
    'Organik, naturel ve geleneksel tarim urunleri icin ozel yesil temali tasarim. Sertifika bilgisi ve QR kod destegi.',
    'label',
    'organic',
    800,
    1280,
    'portrait',
    'esl_101_portrait',
    'split-vertical',
    '{
        "version": "7.0.0",
        "objects": [
            {
                "type": "rect",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 560,
                "fill": "#ecfdf5",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "media"
            },
            {
                "type": "image",
                "left": 0,
                "top": 0,
                "width": 800,
                "height": 560,
                "scaleX": 1,
                "scaleY": 1,
                "customType": "dynamic-image",
                "dynamicField": "{{image_url}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 20,
                "top": 20,
                "width": 170,
                "height": 50,
                "fill": "#166534",
                "rx": 25,
                "ry": 25,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 45,
                "top": 32,
                "text": "ORGANIK",
                "fontSize": 22,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 610,
                "top": 20,
                "width": 170,
                "height": 50,
                "fill": "#15803d",
                "rx": 10,
                "ry": 10,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 625,
                "top": 32,
                "text": "{{production_type}}",
                "fontSize": 16,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#ffffff",
                "dynamicField": "{{production_type}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 0,
                "top": 560,
                "width": 800,
                "height": 720,
                "fill": "#ffffff",
                "selectable": false,
                "evented": false,
                "isBackground": true,
                "regionId": "product"
            },
            {
                "type": "rect",
                "left": 0,
                "top": 560,
                "width": 800,
                "height": 10,
                "fill": "linear-gradient(90deg, #166534 0%, #22c55e 100%)",
                "selectable": false,
                "evented": false
            },
            {
                "type": "rect",
                "left": 25,
                "top": 590,
                "width": 750,
                "height": 670,
                "fill": "#f0fdf4",
                "rx": 20,
                "ry": 20,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 615,
                "text": "{{category}}",
                "fontSize": 18,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{category}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 645,
                "text": "{{product_name}}",
                "fontSize": 42,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#14532d",
                "dynamicField": "{{product_name}}",
                "selectable": true,
                "evented": true,
                "width": 690
            },
            {
                "type": "i-text",
                "left": 55,
                "top": 705,
                "text": "{{origin}} • {{hal.uretici_adi}}",
                "fontSize": 20,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{origin}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 750,
                "width": 690,
                "height": 200,
                "fill": "#ffffff",
                "rx": 16,
                "ry": 16,
                "stroke": "#bbf7d0",
                "strokeWidth": 2,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 90,
                "top": 785,
                "text": "{{current_price}}",
                "fontSize": 90,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{current_price}}",
                "customType": "price",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 420,
                "top": 810,
                "text": "TL",
                "fontSize": 42,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 90,
                "top": 890,
                "text": "/{{unit}}",
                "fontSize": 26,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{unit}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 500,
                "top": 775,
                "width": 220,
                "height": 100,
                "fill": "#f0fdf4",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 530,
                "top": 790,
                "text": "{{previous_price}} TL",
                "fontSize": 22,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#9ca3af",
                "textDecoration": "line-through",
                "dynamicField": "{{previous_price}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 525,
                "top": 825,
                "text": "%{{discount_percent}} TASARRUF",
                "fontSize": 18,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{discount_percent}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 970,
                "width": 690,
                "height": 60,
                "fill": "#dcfce7",
                "rx": 12,
                "ry": 12,
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 85,
                "top": 985,
                "text": "{{campaign_text}}",
                "fontSize": 24,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "dynamicField": "{{campaign_text}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 55,
                "top": 1050,
                "width": 520,
                "height": 190,
                "fill": "#f0fdf4",
                "rx": 12,
                "ry": 12,
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1070,
                "text": "SERTIFIKASYON & IZLENEBILIRLIK",
                "fontSize": 14,
                "fontWeight": "bold",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1100,
                "text": "Sertifika: {{hal.sertifikasyon_kurulusu}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{hal.sertifikasyon_kurulusu}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1130,
                "text": "Uretici: {{hal.uretici_adi}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{hal.uretici_adi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1160,
                "text": "Uretim Yeri: {{hal.uretim_yeri}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{hal.uretim_yeri}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 80,
                "top": 1190,
                "text": "Bildirim: {{hal.ilk_bildirim_tarihi}}",
                "fontSize": 16,
                "fontWeight": "normal",
                "fontFamily": "Inter, sans-serif",
                "fill": "#4ade80",
                "dynamicField": "{{hal.ilk_bildirim_tarihi}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "rect",
                "left": 595,
                "top": 1050,
                "width": 150,
                "height": 190,
                "fill": "#ffffff",
                "rx": 12,
                "ry": 12,
                "stroke": "#bbf7d0",
                "strokeWidth": 1,
                "selectable": false,
                "evented": false
            },
            {
                "type": "image",
                "left": 610,
                "top": 1065,
                "width": 120,
                "height": 120,
                "customType": "qrcode",
                "dynamicField": "{{kunye_no}}",
                "qrValue": "{{kunye_no}}",
                "selectable": true,
                "evented": true
            },
            {
                "type": "i-text",
                "left": 620,
                "top": 1195,
                "text": "Tarimsal",
                "fontSize": 12,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "textAlign": "center",
                "selectable": false,
                "evented": false
            },
            {
                "type": "i-text",
                "left": 615,
                "top": 1212,
                "text": "Izlenebilirlik",
                "fontSize": 12,
                "fontWeight": "600",
                "fontFamily": "Inter, sans-serif",
                "fill": "#166534",
                "textAlign": "center",
                "selectable": false,
                "evented": false
            }
        ],
        "background": "#ffffff"
    }',
    'active',
    now()
);

-- ============================================================================
-- Tamamlandi - 6 Sistem Sablonu Eklendi
-- 1. Manav Premium - Dikey (Media Ust)
-- 2. Manav Video - Ust Bolum Video
-- 3. Et & Balik Premium - Dikey
-- 4. Sut Urunleri - Beyaz Tema
-- 5. Temel Gida - Kompakt Tasarim
-- 6. Organik Urunler - Yesil Premium
-- ============================================================================
