-- Schemas
CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "license";
CREATE SCHEMA IF NOT EXISTS "catalog";
CREATE SCHEMA IF NOT EXISTS "branch";
CREATE SCHEMA IF NOT EXISTS "labels";
CREATE SCHEMA IF NOT EXISTS "media";
CREATE SCHEMA IF NOT EXISTS "devices";
CREATE SCHEMA IF NOT EXISTS "signage";
CREATE SCHEMA IF NOT EXISTS "integration";
CREATE SCHEMA IF NOT EXISTS "audit";
CREATE SCHEMA IF NOT EXISTS "legacy";

