-- Auto-generated indexes from SQLite metadata
-- Review and tune manually with EXPLAIN ANALYZE after migration.

CREATE INDEX IF NOT EXISTS "idx_audit_action" ON "integration"."integration_settings_audit" ("action");
CREATE INDEX IF NOT EXISTS "idx_audit_changed_at" ON "integration"."integration_settings_audit" ("changed_at");
CREATE INDEX IF NOT EXISTS "idx_audit_changed_by" ON "integration"."integration_settings_audit" ("changed_by");
CREATE INDEX IF NOT EXISTS "idx_audit_company_id" ON "integration"."integration_settings_audit" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_audit_integration_type" ON "integration"."integration_settings_audit" ("integration_type");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_action_created" ON "audit"."audit_logs" ("action", "created_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_active" ON "audit"."audit_logs" ("company_id", "archived_at", "created_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_archived" ON "audit"."audit_logs" ("archived_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_company_archived" ON "audit"."audit_logs" ("company_id", "archived_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_company_created" ON "audit"."audit_logs" ("company_id", "created_at");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_entity_type" ON "audit"."audit_logs" ("entity_type");
CREATE INDEX IF NOT EXISTS "idx_audit_settings_id" ON "integration"."integration_settings_audit" ("integration_settings_id");
CREATE INDEX IF NOT EXISTS "idx_bbo_active" ON "branch"."bundle_branch_overrides" ("bundle_id", "branch_id", "deleted_at");
CREATE INDEX IF NOT EXISTS "idx_bbo_available" ON "branch"."bundle_branch_overrides" ("branch_id", "is_available");
CREATE INDEX IF NOT EXISTS "idx_bbo_branch" ON "branch"."bundle_branch_overrides" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_bbo_bundle" ON "branch"."bundle_branch_overrides" ("bundle_id");
CREATE INDEX IF NOT EXISTS "idx_bbo_deleted" ON "branch"."bundle_branch_overrides" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_bbo_source" ON "branch"."bundle_branch_overrides" ("source");
CREATE INDEX IF NOT EXISTS "idx_bbph_branch_date" ON "branch"."bundle_branch_price_history" ("branch_id", "changed_at");
CREATE INDEX IF NOT EXISTS "idx_bbph_bundle_branch" ON "branch"."bundle_branch_price_history" ("bundle_id", "branch_id");
CREATE INDEX IF NOT EXISTS "idx_bbph_bundle_date" ON "branch"."bundle_branch_price_history" ("bundle_id", "changed_at");
CREATE INDEX IF NOT EXISTS "idx_bil_branch" ON "branch"."branch_import_logs" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_bil_company" ON "branch"."branch_import_logs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_bil_date" ON "branch"."branch_import_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_bil_status" ON "branch"."branch_import_logs" ("status");
CREATE INDEX IF NOT EXISTS "idx_bph_branch_date" ON "branch"."branch_price_history" ("branch_id", "changed_at");
CREATE INDEX IF NOT EXISTS "idx_bph_product_branch" ON "branch"."branch_price_history" ("product_id", "branch_id");
CREATE INDEX IF NOT EXISTS "idx_bph_product_date" ON "branch"."branch_price_history" ("product_id", "changed_at");
CREATE INDEX IF NOT EXISTS "idx_bph_reason" ON "branch"."branch_price_history" ("change_reason");
CREATE INDEX IF NOT EXISTS "idx_branch_hal_overrides_active" ON "integration"."product_branch_hal_overrides" ("hal_data_id", "branch_id", "deleted_at");
CREATE INDEX IF NOT EXISTS "idx_branch_hal_overrides_branch" ON "integration"."product_branch_hal_overrides" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_branch_hal_overrides_hal_data" ON "integration"."product_branch_hal_overrides" ("hal_data_id");
CREATE INDEX IF NOT EXISTS "idx_branches_active" ON "branch"."branches" ("company_id", "is_active");
CREATE INDEX IF NOT EXISTS "idx_branches_company" ON "branch"."branches" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_branches_company_type_parent" ON "branch"."branches" ("company_id", "type", "parent_id");
CREATE INDEX IF NOT EXISTS "idx_branches_external_code" ON "branch"."branches" ("company_id", "external_code");
CREATE INDEX IF NOT EXISTS "idx_branches_parent" ON "branch"."branches" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_branches_type" ON "branch"."branches" ("type");
CREATE INDEX IF NOT EXISTS "idx_bundle_items_bundle" ON "catalog"."bundle_items" ("bundle_id");
CREATE INDEX IF NOT EXISTS "idx_bundle_items_product" ON "catalog"."bundle_items" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_bundle_price_history_bundle" ON "catalog"."bundle_price_history" ("bundle_id");
CREATE INDEX IF NOT EXISTS "idx_bundle_price_history_date" ON "catalog"."bundle_price_history" ("changed_at");
CREATE INDEX IF NOT EXISTS "idx_bundles_company" ON "catalog"."bundles" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_bundles_sku" ON "catalog"."bundles" ("company_id", "sku");
CREATE INDEX IF NOT EXISTS "idx_bundles_slug" ON "catalog"."bundles" ("company_id", "slug");
CREATE INDEX IF NOT EXISTS "idx_bundles_status" ON "catalog"."bundles" ("status");
CREATE INDEX IF NOT EXISTS "idx_bundles_type" ON "catalog"."bundles" ("type");
CREATE INDEX IF NOT EXISTS "idx_categories_is_demo" ON "catalog"."categories" ("is_demo");
CREATE INDEX IF NOT EXISTS "idx_companies_code" ON "core"."companies" ("code");
CREATE INDEX IF NOT EXISTS "idx_companies_domain" ON "core"."companies" ("domain");
CREATE INDEX IF NOT EXISTS "idx_companies_slug" ON "core"."companies" ("slug");
CREATE INDEX IF NOT EXISTS "idx_companies_status" ON "core"."companies" ("status");
CREATE INDEX IF NOT EXISTS "idx_companies_storage_limit" ON "core"."companies" ("storage_limit");
CREATE INDEX IF NOT EXISTS "idx_dca_active" ON "devices"."device_content_assignments" ("content_type", "status", "device_id");
CREATE INDEX IF NOT EXISTS "idx_device_alerts_device" ON "devices"."device_alerts" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_commands_device" ON "devices"."device_commands" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_commands_status" ON "devices"."device_commands" ("status");
CREATE INDEX IF NOT EXISTS "idx_device_group_members_device" ON "devices"."device_group_members" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_group_members_group" ON "devices"."device_group_members" ("group_id");
CREATE INDEX IF NOT EXISTS "idx_device_groups_company" ON "devices"."device_groups" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_device_groups_parent" ON "devices"."device_groups" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_device_heartbeats_created" ON "devices"."device_heartbeats" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_device_heartbeats_device" ON "devices"."device_heartbeats" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_heartbeats_device_status" ON "devices"."device_heartbeats" ("device_id", "status");
CREATE INDEX IF NOT EXISTS "idx_device_logs_created" ON "devices"."device_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_device_logs_device" ON "devices"."device_logs" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_logs_status" ON "devices"."device_logs" ("status");
CREATE INDEX IF NOT EXISTS "idx_device_tokens_device" ON "devices"."device_tokens" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_device_tokens_hash" ON "devices"."device_tokens" ("token_hash");
CREATE INDEX IF NOT EXISTS "idx_device_tokens_token" ON "devices"."device_tokens" ("token");
CREATE INDEX IF NOT EXISTS "idx_devices_adapter" ON "devices"."devices" ("adapter_id");
CREATE INDEX IF NOT EXISTS "idx_devices_approval_status" ON "devices"."devices" ("approval_status");
CREATE INDEX IF NOT EXISTS "idx_devices_branch" ON "devices"."devices" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_devices_branch_type_status" ON "devices"."devices" ("branch_id", "type", "status");
CREATE INDEX IF NOT EXISTS "idx_devices_brand" ON "devices"."devices" ("device_brand");
CREATE INDEX IF NOT EXISTS "idx_devices_comm_mode" ON "devices"."devices" ("communication_mode");
CREATE INDEX IF NOT EXISTS "idx_devices_company" ON "devices"."devices" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_devices_company_branch" ON "devices"."devices" ("company_id", "branch_id");
CREATE INDEX IF NOT EXISTS "idx_devices_company_type_status" ON "devices"."devices" ("company_id", "type", "status");
CREATE INDEX IF NOT EXISTS "idx_devices_current_playlist" ON "devices"."devices" ("current_playlist_id");
CREATE INDEX IF NOT EXISTS "idx_devices_device_token" ON "devices"."devices" ("device_token");
CREATE INDEX IF NOT EXISTS "idx_devices_fingerprint" ON "devices"."devices" ("fingerprint");
CREATE INDEX IF NOT EXISTS "idx_devices_group" ON "devices"."devices" ("group_id");
CREATE INDEX IF NOT EXISTS "idx_devices_mqtt_client" ON "devices"."devices" ("mqtt_client_id");
CREATE INDEX IF NOT EXISTS "idx_devices_status" ON "devices"."devices" ("status");
CREATE INDEX IF NOT EXISTS "idx_devices_sync_code" ON "devices"."devices" ("sync_code");
CREATE INDEX IF NOT EXISTS "idx_devices_type" ON "devices"."devices" ("type");
CREATE INDEX IF NOT EXISTS "idx_firmware_updates_active" ON "devices"."firmware_updates" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_firmware_updates_device_type" ON "devices"."firmware_updates" ("device_type");
CREATE INDEX IF NOT EXISTS "idx_firmware_updates_released" ON "devices"."firmware_updates" ("released_at");
CREATE INDEX IF NOT EXISTS "idx_firmware_updates_version" ON "devices"."firmware_updates" ("version");
CREATE INDEX IF NOT EXISTS "idx_gateway_commands_gateway" ON "devices"."gateway_commands" ("gateway_id");
CREATE INDEX IF NOT EXISTS "idx_gateway_commands_pending" ON "devices"."gateway_commands" ("gateway_id", "status") WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS "idx_gateway_commands_status" ON "devices"."gateway_commands" ("status");
CREATE INDEX IF NOT EXISTS "idx_gateway_devices_device" ON "devices"."gateway_devices" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_gateway_devices_gateway" ON "devices"."gateway_devices" ("gateway_id");
CREATE INDEX IF NOT EXISTS "idx_gateways_api_key" ON "devices"."gateways" ("api_key");
CREATE INDEX IF NOT EXISTS "idx_gateways_company" ON "devices"."gateways" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_gateways_status" ON "devices"."gateways" ("status");
CREATE INDEX IF NOT EXISTS "idx_hal_dist_company" ON "integration"."hal_distribution_logs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_hal_dist_kunye" ON "integration"."hal_distribution_logs" ("kunye_no");
CREATE INDEX IF NOT EXISTS "idx_hal_dist_product" ON "integration"."hal_distribution_logs" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_aps_company" ON "devices"."hanshow_aps" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_aps_mac" ON "devices"."hanshow_aps" ("mac_address");
CREATE INDEX IF NOT EXISTS "idx_hanshow_esls_company" ON "devices"."hanshow_esls" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_esls_esl_id" ON "devices"."hanshow_esls" ("esl_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_esls_product" ON "devices"."hanshow_esls" ("current_product_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_esls_status" ON "devices"."hanshow_esls" ("status");
CREATE INDEX IF NOT EXISTS "idx_hanshow_queue_company" ON "devices"."hanshow_queue" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_queue_created" ON "devices"."hanshow_queue" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_hanshow_queue_esl" ON "devices"."hanshow_queue" ("esl_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_queue_session" ON "devices"."hanshow_queue" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_hanshow_queue_status" ON "devices"."hanshow_queue" ("status");
CREATE INDEX IF NOT EXISTS "idx_hanshow_settings_company_scope" ON "devices"."hanshow_settings" ("company_id", "scope");
CREATE INDEX IF NOT EXISTS "idx_hanshow_settings_scope" ON "devices"."hanshow_settings" ("scope");
CREATE INDEX IF NOT EXISTS "idx_integration_settings_active" ON "integration"."integration_settings" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_integration_settings_company" ON "integration"."integration_settings" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_integration_settings_lookup" ON "integration"."integration_settings" ("integration_type", "scope", "company_id");
CREATE INDEX IF NOT EXISTS "idx_integration_settings_scope" ON "integration"."integration_settings" ("scope");
CREATE INDEX IF NOT EXISTS "idx_integration_settings_type" ON "integration"."integration_settings" ("integration_type");
CREATE INDEX IF NOT EXISTS "idx_label_sizes_active" ON "labels"."label_sizes" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_label_sizes_company" ON "labels"."label_sizes" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_label_sizes_sort" ON "labels"."label_sizes" ("sort_order");
CREATE INDEX IF NOT EXISTS "idx_ldp_category" ON "license"."license_device_pricing" ("device_category");
CREATE INDEX IF NOT EXISTS "idx_ldp_license" ON "license"."license_device_pricing" ("license_id");
CREATE INDEX IF NOT EXISTS "idx_license_plans_is_active" ON "license"."license_plans" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_license_plans_is_unlimited" ON "license"."license_plans" ("is_unlimited");
CREATE INDEX IF NOT EXISTS "idx_license_plans_plan_type" ON "license"."license_plans" ("plan_type");
CREATE INDEX IF NOT EXISTS "idx_license_plans_slug" ON "license"."license_plans" ("slug");
CREATE INDEX IF NOT EXISTS "idx_license_plans_status" ON "license"."license_plans" ("status");
CREATE INDEX IF NOT EXISTS "idx_license_plans_type" ON "license"."license_plans" ("plan_type");
CREATE INDEX IF NOT EXISTS "idx_licenses_company" ON "license"."licenses" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_licenses_company_status" ON "license"."licenses" ("company_id", "status");
CREATE INDEX IF NOT EXISTS "idx_licenses_plan_id" ON "license"."licenses" ("plan_id");
CREATE INDEX IF NOT EXISTS "idx_licenses_status" ON "license"."licenses" ("status");
CREATE INDEX IF NOT EXISTS "idx_licenses_valid_until" ON "license"."licenses" ("valid_until");
CREATE INDEX IF NOT EXISTS "idx_media_company" ON "media"."media" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_media_company_scope" ON "media"."media" ("company_id", "scope");
CREATE INDEX IF NOT EXISTS "idx_media_company_type" ON "media"."media" ("company_id", "media_type");
CREATE INDEX IF NOT EXISTS "idx_media_folder" ON "media"."media" ("folder_id");
CREATE INDEX IF NOT EXISTS "idx_media_folders_company" ON "media"."media_folders" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_media_folders_parent" ON "media"."media_folders" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_media_is_public" ON "media"."media" ("is_public");
CREATE INDEX IF NOT EXISTS "idx_media_scope" ON "media"."media" ("scope");
CREATE INDEX IF NOT EXISTS "idx_media_status" ON "media"."media" ("status");
CREATE INDEX IF NOT EXISTS "idx_media_type" ON "media"."media" ("file_type");
CREATE INDEX IF NOT EXISTS "idx_mqtt_settings_company" ON "devices"."mqtt_settings" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_notification_recipients_status" ON "audit"."notification_recipients" ("status");
CREATE INDEX IF NOT EXISTS "idx_notification_recipients_user" ON "audit"."notification_recipients" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_notifications_expires" ON "audit"."notifications" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_notifications_type" ON "audit"."notifications" ("type");
CREATE INDEX IF NOT EXISTS "idx_payment_settings_company" ON "license"."payment_settings" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_payment_settings_provider" ON "license"."payment_settings" ("provider");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_basket" ON "license"."payment_transactions" ("basket_id");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_company" ON "license"."payment_transactions" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_created" ON "license"."payment_transactions" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_license" ON "license"."payment_transactions" ("license_id");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_provider_id" ON "license"."payment_transactions" ("provider_transaction_id");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_status" ON "license"."payment_transactions" ("status");
CREATE INDEX IF NOT EXISTS "idx_payment_trans_user" ON "license"."payment_transactions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_payment_transactions_company" ON "license"."payment_transactions" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_payment_transactions_license" ON "license"."payment_transactions" ("license_id");
CREATE INDEX IF NOT EXISTS "idx_payment_transactions_plan_id" ON "license"."payment_transactions" ("plan_id");
CREATE INDEX IF NOT EXISTS "idx_payment_transactions_reference" ON "license"."payment_transactions" ("reference_no");
CREATE INDEX IF NOT EXISTS "idx_payment_transactions_status" ON "license"."payment_transactions" ("status");
CREATE INDEX IF NOT EXISTS "idx_pbo_active" ON "branch"."product_branch_overrides" ("product_id", "branch_id", "deleted_at");
CREATE INDEX IF NOT EXISTS "idx_pbo_available" ON "branch"."product_branch_overrides" ("branch_id", "is_available");
CREATE INDEX IF NOT EXISTS "idx_pbo_branch" ON "branch"."product_branch_overrides" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_pbo_campaign" ON "branch"."product_branch_overrides" ("branch_id", "campaign_start", "campaign_end");
CREATE INDEX IF NOT EXISTS "idx_pbo_deleted" ON "branch"."product_branch_overrides" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_pbo_product" ON "branch"."product_branch_overrides" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_pbo_scope" ON "branch"."product_branch_overrides" ("override_scope");
CREATE INDEX IF NOT EXISTS "idx_pbo_source" ON "branch"."product_branch_overrides" ("source");
CREATE INDEX IF NOT EXISTS "idx_playlists_company" ON "signage"."playlists" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_playlists_orientation" ON "signage"."playlists" ("orientation");
CREATE INDEX IF NOT EXISTS "idx_playlists_template" ON "signage"."playlists" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_price_history_changed" ON "catalog"."price_history" ("changed_at");
CREATE INDEX IF NOT EXISTS "idx_price_history_product" ON "catalog"."price_history" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_product_hal_data_company" ON "integration"."product_hal_data" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_product_hal_data_kunye" ON "integration"."product_hal_data" ("kunye_no");
CREATE INDEX IF NOT EXISTS "idx_product_hal_data_product" ON "integration"."product_hal_data" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_production_types_is_demo" ON "catalog"."production_types" ("is_demo");
CREATE INDEX IF NOT EXISTS "idx_products_assigned_device" ON "catalog"."products" ("assigned_device_id");
CREATE INDEX IF NOT EXISTS "idx_products_assigned_template" ON "catalog"."products" ("assigned_template_id");
CREATE INDEX IF NOT EXISTS "idx_products_barcode" ON "catalog"."products" ("barcode");
CREATE INDEX IF NOT EXISTS "idx_products_category" ON "catalog"."products" ("category");
CREATE INDEX IF NOT EXISTS "idx_products_company" ON "catalog"."products" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_products_erp_product_id" ON "catalog"."products" ("erp_product_id");
CREATE INDEX IF NOT EXISTS "idx_products_group" ON "catalog"."products" ("group");
CREATE INDEX IF NOT EXISTS "idx_products_is_demo" ON "catalog"."products" ("is_demo");
CREATE INDEX IF NOT EXISTS "idx_products_sku" ON "catalog"."products" ("sku");
CREATE INDEX IF NOT EXISTS "idx_products_status" ON "catalog"."products" ("status");
CREATE INDEX IF NOT EXISTS "idx_products_vat_updated_at" ON "catalog"."products" ("vat_updated_at");
CREATE INDEX IF NOT EXISTS "idx_queue_items_device" ON "labels"."render_queue_items" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_queue_items_queue" ON "labels"."render_queue_items" ("queue_id", "status");
CREATE INDEX IF NOT EXISTS "idx_rate_limits_cleanup" ON "core"."rate_limits" ("window_start");
CREATE INDEX IF NOT EXISTS "idx_render_cache_company" ON "labels"."render_cache" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_render_cache_key" ON "labels"."render_cache" ("cache_key");
CREATE INDEX IF NOT EXISTS "idx_render_cache_lookup" ON "labels"."render_cache" ("company_id", "product_id", "template_id");
CREATE INDEX IF NOT EXISTS "idx_render_cache_product" ON "labels"."render_cache" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_render_cache_status" ON "labels"."render_cache" ("status");
CREATE INDEX IF NOT EXISTS "idx_render_cache_template" ON "labels"."render_cache" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_render_jobs_batch" ON "labels"."render_jobs" ("batch_id");
CREATE INDEX IF NOT EXISTS "idx_render_jobs_company" ON "labels"."render_jobs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_render_jobs_priority" ON "labels"."render_jobs" ("priority", "created_at");
CREATE INDEX IF NOT EXISTS "idx_render_jobs_status" ON "labels"."render_jobs" ("status");
CREATE INDEX IF NOT EXISTS "idx_render_queue_batch_id" ON "labels"."render_queue" ("batch_id");
CREATE INDEX IF NOT EXISTS "idx_render_queue_company" ON "labels"."render_queue" ("company_id", "status");
CREATE INDEX IF NOT EXISTS "idx_render_queue_priority" ON "labels"."render_queue" ("priority", "created_at");
CREATE INDEX IF NOT EXISTS "idx_render_queue_rendered_image" ON "labels"."render_queue" ("rendered_image_path");
CREATE INDEX IF NOT EXISTS "idx_render_queue_retry" ON "labels"."render_queue" ("next_retry_at", "status");
CREATE INDEX IF NOT EXISTS "idx_render_queue_scheduled" ON "labels"."render_queue" ("scheduled_at", "status");
CREATE INDEX IF NOT EXISTS "idx_render_queue_status" ON "labels"."render_queue" ("status");
CREATE INDEX IF NOT EXISTS "idx_render_queue_worker" ON "labels"."render_queue" ("status", "priority", "scheduled_at", "created_at");
CREATE INDEX IF NOT EXISTS "idx_renders_company" ON "labels"."product_renders" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_renders_product" ON "labels"."product_renders" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_renders_template" ON "labels"."product_renders" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_renders_versions" ON "labels"."product_renders" ("product_id", "product_version", "template_version");
CREATE INDEX IF NOT EXISTS "idx_schedules_company" ON "signage"."schedules" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_expires" ON "core"."sessions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_sessions_user" ON "core"."sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_settings_company" ON "core"."settings" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_settings_user" ON "core"."settings" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_storage_company" ON "media"."company_storage_usage" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_storage_total" ON "media"."company_storage_usage" ("total_bytes");
CREATE INDEX IF NOT EXISTS "idx_stream_logs_created" ON "signage"."stream_access_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_stream_logs_device" ON "signage"."stream_access_logs" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_stream_logs_token" ON "signage"."stream_access_logs" ("stream_token");
CREATE INDEX IF NOT EXISTS "idx_sync_requests_brand" ON "devices"."device_sync_requests" ("brand");
CREATE INDEX IF NOT EXISTS "idx_sync_requests_device_type" ON "devices"."device_sync_requests" ("device_type");
CREATE INDEX IF NOT EXISTS "idx_sync_requests_status" ON "devices"."device_sync_requests" ("status");
CREATE INDEX IF NOT EXISTS "idx_sync_requests_sync_code" ON "devices"."device_sync_requests" ("sync_code");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_depo_mapping_branch" ON "integration"."tamsoft_depo_mapping" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_depo_mapping_company" ON "integration"."tamsoft_depo_mapping" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_settings_company" ON "integration"."tamsoft_settings" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_sync_logs_company" ON "integration"."tamsoft_sync_logs" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_tokens_company" ON "integration"."tamsoft_tokens" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_tamsoft_tokens_expires" ON "integration"."tamsoft_tokens" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_templates_category" ON "labels"."templates" ("category");
CREATE INDEX IF NOT EXISTS "idx_templates_company" ON "labels"."templates" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_templates_company_scope" ON "labels"."templates" ("company_id", "scope");
CREATE INDEX IF NOT EXISTS "idx_templates_grid_layout" ON "labels"."templates" ("grid_layout");
CREATE INDEX IF NOT EXISTS "idx_templates_is_demo" ON "labels"."templates" ("is_demo");
CREATE INDEX IF NOT EXISTS "idx_templates_layout_type" ON "labels"."templates" ("layout_type");
CREATE INDEX IF NOT EXISTS "idx_templates_public" ON "labels"."templates" ("is_public");
CREATE INDEX IF NOT EXISTS "idx_templates_scope" ON "labels"."templates" ("scope");
CREATE INDEX IF NOT EXISTS "idx_templates_status" ON "labels"."templates" ("status");
CREATE INDEX IF NOT EXISTS "idx_templates_target_device" ON "labels"."templates" ("target_device_type");
CREATE INDEX IF NOT EXISTS "idx_templates_type" ON "labels"."templates" ("type");
CREATE INDEX IF NOT EXISTS "idx_transcode_queue_company" ON "signage"."transcode_queue" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_transcode_queue_media" ON "signage"."transcode_queue" ("media_id");
CREATE INDEX IF NOT EXISTS "idx_transcode_queue_priority" ON "signage"."transcode_queue" ("priority", "created_at");
CREATE INDEX IF NOT EXISTS "idx_transcode_queue_status" ON "signage"."transcode_queue" ("status");
CREATE INDEX IF NOT EXISTS "idx_transcode_variants_company" ON "signage"."transcode_variants" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_transcode_variants_media" ON "signage"."transcode_variants" ("media_id");
CREATE INDEX IF NOT EXISTS "idx_transcode_variants_status" ON "signage"."transcode_variants" ("status");
CREATE INDEX IF NOT EXISTS "idx_uba_branch" ON "branch"."user_branch_access" ("branch_id");
CREATE INDEX IF NOT EXISTS "idx_uba_default" ON "branch"."user_branch_access" ("user_id", "is_default");
CREATE INDEX IF NOT EXISTS "idx_uba_user" ON "branch"."user_branch_access" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_notif_prefs_user" ON "audit"."user_notification_preferences" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_users_company" ON "core"."users" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "core"."users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_role" ON "core"."users" ("role");
CREATE INDEX IF NOT EXISTS "idx_users_status" ON "core"."users" ("status");
CREATE INDEX IF NOT EXISTS "idx_web_template_assignments_active" ON "signage"."web_template_assignments" ("is_active", "device_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_assignments_company" ON "signage"."web_template_assignments" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_assignments_device" ON "signage"."web_template_assignments" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_assignments_template" ON "signage"."web_template_assignments" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_versions_number" ON "signage"."web_template_versions" ("template_id", "version_number");
CREATE INDEX IF NOT EXISTS "idx_web_template_versions_template" ON "signage"."web_template_versions" ("template_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_widgets_category" ON "signage"."web_template_widgets" ("category");
CREATE INDEX IF NOT EXISTS "idx_web_template_widgets_company" ON "signage"."web_template_widgets" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_web_template_widgets_slug" ON "signage"."web_template_widgets" ("slug");
CREATE INDEX IF NOT EXISTS "idx_web_templates_company" ON "signage"."web_templates" ("company_id");
CREATE INDEX IF NOT EXISTS "idx_web_templates_created" ON "signage"."web_templates" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_web_templates_scope" ON "signage"."web_templates" ("scope");
CREATE INDEX IF NOT EXISTS "idx_web_templates_slug" ON "signage"."web_templates" ("slug");
CREATE INDEX IF NOT EXISTS "idx_web_templates_status" ON "signage"."web_templates" ("status");
CREATE INDEX IF NOT EXISTS "idx_web_templates_type" ON "signage"."web_templates" ("template_type");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_bundle_items_unique" ON "catalog"."bundle_items" ("bundle_id", "product_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_dca_one_active_playlist_per_device" ON "devices"."device_content_assignments" ("device_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_devices_stream_token" ON "devices"."devices" ("stream_token") WHERE stream_token IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_permissions_role_resource" ON "core"."permissions" ("role", "resource");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_products_company_sku" ON "catalog"."products" ("company_id", "sku");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_renders_unique" ON "labels"."product_renders" ("product_id", "template_id", "device_type", "locale");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_branches_company_id_code" ON "branch"."branches" ("company_id", "code");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_bundle_branch_overrides_bundle_id_branch_id" ON "branch"."bundle_branch_overrides" ("bundle_id", "branch_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_companies_slug" ON "core"."companies" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_company_storage_usage_company_id" ON "media"."company_storage_usage" ("company_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_device_group_members_group_id_device_id" ON "devices"."device_group_members" ("group_id", "device_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_device_sync_requests_sync_code" ON "devices"."device_sync_requests" ("sync_code");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_device_tokens_token" ON "devices"."device_tokens" ("token");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_gateway_devices_gateway_id_device_id" ON "devices"."gateway_devices" ("gateway_id", "device_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_gateways_api_key" ON "devices"."gateways" ("api_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_hanshow_aps_company_id_ap_id" ON "devices"."hanshow_aps" ("company_id", "ap_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_hanshow_aps_company_id_mac_address" ON "devices"."hanshow_aps" ("company_id", "mac_address");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_hanshow_esls_esl_id" ON "devices"."hanshow_esls" ("esl_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_hanshow_queue_session_id" ON "devices"."hanshow_queue" ("session_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_hanshow_settings_company_id" ON "devices"."hanshow_settings" ("company_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_integration_settings_integration_type_scope_company_id" ON "integration"."integration_settings" ("integration_type", "scope", "company_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_license_device_pricing_license_id_device_category" ON "license"."license_device_pricing" ("license_id", "device_category");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_license_plans_slug" ON "license"."license_plans" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_licenses_company_id" ON "license"."licenses" ("company_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_licenses_license_key" ON "license"."licenses" ("license_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_migrations_name" ON "core"."migrations" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_notification_settings_user_id" ON "audit"."notification_settings" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_product_branch_hal_overrides_hal_data_id_branch_id" ON "integration"."product_branch_hal_overrides" ("hal_data_id", "branch_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_product_branch_overrides_product_id_branch_id" ON "branch"."product_branch_overrides" ("product_id", "branch_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_product_hal_data_product_id" ON "integration"."product_hal_data" ("product_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_render_cache_company_id_product_id_template_id" ON "labels"."render_cache" ("company_id", "product_id", "template_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_sessions_refresh_token_hash" ON "core"."sessions" ("refresh_token_hash");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_sessions_token_hash" ON "core"."sessions" ("token_hash");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_tamsoft_depo_mapping_company_id_tamsoft_depo_id" ON "integration"."tamsoft_depo_mapping" ("company_id", "tamsoft_depo_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_tamsoft_settings_company_id" ON "integration"."tamsoft_settings" ("company_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_branch_access_user_id_branch_id" ON "branch"."user_branch_access" ("user_id", "branch_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_notification_preferences_user_id" ON "audit"."user_notification_preferences" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email" ON "core"."users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_web_template_assignments_template_id_device_id" ON "signage"."web_template_assignments" ("template_id", "device_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_web_template_widgets_slug" ON "signage"."web_template_widgets" ("slug");
