<?php
/**
 * Manav Reyonu Demo Ürünler Seed
 * Türkiye pazarı için gerçekçi manav ürünleri
 *
 * Tüm ürün kartı alanlarını içerir:
 * - Temel: sku, barcode, name, category, subcategory, brand, origin, unit
 * - Fiyat: current_price, previous_price, campaign_price (campaign_text olarak), vat_rate, discount_percent
 * - Stok: stock, weight, shelf_location, supplier_code, kunye_no
 * - Ek: description, image_url, production_type, valid_from, valid_until, is_featured
 * - Tarihler: price_updated_at, previous_price_updated_at
 */

require_once __DIR__ . '/../../config.php';
require_once CORE_PATH . '/Database.php';

$db = Database::getInstance();

// Önce mevcut firma ID'sini al
$company = $db->fetch("SELECT id FROM companies LIMIT 1");
if (!$company) {
    die("Firma bulunamadı. Önce bir firma oluşturun.\n");
}
$companyId = $company['id'];

$isCli = php_sapi_name() === 'cli';
if ($isCli) {
    echo "Firma ID: $companyId\n";
    echo "Manav ürünleri ekleniyor...\n\n";
}

// Üretim tipleri ekle
$productionTypes = [
    ['name' => 'Konvansiyonel', 'color' => '#868e96', 'description' => 'Standart tarım yöntemleri'],
    ['name' => 'Organik', 'color' => '#40c057', 'description' => 'Organik sertifikalı ürünler'],
    ['name' => 'Naturel', 'color' => '#fab005', 'description' => 'Doğal yöntemlerle üretilmiş'],
    ['name' => 'Geleneksel Tarım', 'color' => '#228be6', 'description' => 'Geleneksel Türk tarımı'],
];

foreach ($productionTypes as $pt) {
    $existing = $db->fetch("SELECT id FROM production_types WHERE company_id = ? AND name = ?", [$companyId, $pt['name']]);
    if (!$existing) {
        $db->insert('production_types', [
            'id' => $db->generateUuid(),
            'company_id' => $companyId,
            'name' => $pt['name'],
            'slug' => strtolower(str_replace(['ı', 'ö', 'ü', 'ş', 'ğ', 'ç', ' '], ['i', 'o', 'u', 's', 'g', 'c', '-'], $pt['name'])),
            'color' => $pt['color'],
            'description' => $pt['description'],
            'sort_order' => 0,
            'status' => 'active',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);
        if ($isCli) echo "Üretim tipi eklendi: {$pt['name']}\n";
    }
}

// Manav ürünleri - Türkiye pazarı için gerçekçi veriler
$products = [
    // MEYVELER
    [
        'sku' => 'MNV-MYV-001',
        'barcode' => '8690001000001',
        'name' => 'Elma Golden Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli Üretim',
        'origin' => 'Türkiye - Isparta',
        'unit' => 'kg',
        'current_price' => 34.90,
        'previous_price' => 39.90,
        'vat_rate' => 1,
        'discount_percent' => 12.5,
        'campaign_text' => 'Haftalık İndirim',
        'weight' => 1.0,
        'stock' => 150,
        'shelf_location' => 'A-01-01',
        'supplier_code' => 'SUP-001',
        'kunye_no' => '2070001000001',
        'description' => 'Taze golden cinsi elma, yerli üretim',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 1,
        'price_valid_until' => '2026-01-20',
        'price_updated_at' => '2026-01-10 10:30:00',
        'previous_price_updated_at' => '2026-01-05 14:00:00',
    ],
    [
        'sku' => 'MNV-MYV-002',
        'barcode' => '8690001000002',
        'name' => 'Elma Starking Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli Üretim',
        'origin' => 'Türkiye - Niğde',
        'unit' => 'kg',
        'current_price' => 32.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 200,
        'shelf_location' => 'A-01-02',
        'supplier_code' => 'SUP-001',
        'kunye_no' => '2070001000002',
        'description' => 'Starking elma, kırmızı ve tatlı',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-MYV-003',
        'barcode' => '8690001000003',
        'name' => 'Armut Deveci Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli Üretim',
        'origin' => 'Türkiye - Ankara',
        'unit' => 'kg',
        'current_price' => 44.90,
        'previous_price' => 49.90,
        'vat_rate' => 1,
        'discount_percent' => 10,
        'campaign_text' => 'Sezon İndirimi',
        'weight' => 1.0,
        'stock' => 80,
        'shelf_location' => 'A-02-01',
        'supplier_code' => 'SUP-002',
        'kunye_no' => '2070001000003',
        'description' => 'Deveci armut, sulu ve tatlı',
        'production_type' => 'Geleneksel Tarım',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-11 11:15:00',
        'previous_price_updated_at' => '2026-01-08 16:30:00',
    ],
    [
        'sku' => 'MNV-MYV-004',
        'barcode' => '8690001000004',
        'name' => 'Portakal Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Finike',
        'origin' => 'Türkiye - Antalya',
        'unit' => 'kg',
        'current_price' => 19.90,
        'previous_price' => 24.90,
        'vat_rate' => 1,
        'discount_percent' => 20,
        'campaign_text' => 'Kış Festivali',
        'weight' => 1.0,
        'stock' => 500,
        'shelf_location' => 'A-03-01',
        'supplier_code' => 'SUP-003',
        'kunye_no' => '2070001000004',
        'description' => 'Finike portakalı, C vitamini deposu',
        'production_type' => 'Naturel',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => '2026-01-09 13:45:00',
    ],
    [
        'sku' => 'MNV-MYV-005',
        'barcode' => '8690001000005',
        'name' => 'Mandalina Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Bodrum',
        'origin' => 'Türkiye - Muğla',
        'unit' => 'kg',
        'current_price' => 24.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 300,
        'shelf_location' => 'A-03-02',
        'supplier_code' => 'SUP-003',
        'kunye_no' => '2070001000005',
        'description' => 'Bodrum mandalinası, kolay soyulur',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-MYV-006',
        'barcode' => '8690001000006',
        'name' => 'Muz Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Anamur',
        'origin' => 'Türkiye - Mersin',
        'unit' => 'kg',
        'current_price' => 54.90,
        'previous_price' => 59.90,
        'vat_rate' => 1,
        'discount_percent' => 8.3,
        'campaign_text' => 'Yerli Muz Günleri',
        'weight' => 1.0,
        'stock' => 120,
        'shelf_location' => 'A-04-01',
        'supplier_code' => 'SUP-004',
        'kunye_no' => '2070001000006',
        'description' => 'Anamur muzu, yerli üretim',
        'production_type' => 'Naturel',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-10 10:30:00',
        'previous_price_updated_at' => '2026-01-07 10:00:00',
    ],
    [
        'sku' => 'MNV-MYV-007',
        'barcode' => '8690001000007',
        'name' => 'Üzüm Sultani Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Ege',
        'origin' => 'Türkiye - Manisa',
        'unit' => 'kg',
        'current_price' => 39.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 90,
        'shelf_location' => 'A-05-01',
        'supplier_code' => 'SUP-005',
        'kunye_no' => '2070001000007',
        'description' => 'Sultani üzüm, çekirdeksiz',
        'production_type' => 'Organik',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-11 11:15:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-MYV-008',
        'barcode' => '8690001000008',
        'name' => 'Nar Kg',
        'category' => 'MEYVE',
        'subcategory' => 'MANAV',
        'brand' => 'Hicaz',
        'origin' => 'Türkiye - Gaziantep',
        'unit' => 'kg',
        'current_price' => 29.90,
        'previous_price' => 34.90,
        'vat_rate' => 1,
        'discount_percent' => 14.3,
        'campaign_text' => 'Antioksidan Festivali',
        'weight' => 1.0,
        'stock' => 70,
        'shelf_location' => 'A-06-01',
        'supplier_code' => 'SUP-006',
        'kunye_no' => '2070001000008',
        'description' => 'Hicaz narı, ekşi-tatlı',
        'production_type' => 'Geleneksel Tarım',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-09 08:45:00',
        'previous_price_updated_at' => '2026-01-05 14:00:00',
    ],

    // SEBZELER
    [
        'sku' => 'MNV-SBZ-001',
        'barcode' => '8690002000001',
        'name' => 'Domates Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Antalya',
        'origin' => 'Türkiye - Antalya',
        'unit' => 'kg',
        'current_price' => 24.90,
        'previous_price' => 29.90,
        'vat_rate' => 1,
        'discount_percent' => 16.7,
        'campaign_text' => 'Salata Festivali',
        'weight' => 1.0,
        'stock' => 400,
        'shelf_location' => 'B-01-01',
        'supplier_code' => 'SUP-007',
        'kunye_no' => '2070002000001',
        'description' => 'Sofralık domates, kırmızı ve lezzetli',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => '2026-01-10',
    ],
    [
        'sku' => 'MNV-SBZ-002',
        'barcode' => '8690002000002',
        'name' => 'Domates Salkım Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Premium',
        'origin' => 'Türkiye - Antalya',
        'unit' => 'kg',
        'current_price' => 34.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 150,
        'shelf_location' => 'B-01-02',
        'supplier_code' => 'SUP-007',
        'kunye_no' => '2070002000002',
        'description' => 'Salkım domates, taze ve aromatik',
        'production_type' => 'Organik',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-SBZ-003',
        'barcode' => '8690002000003',
        'name' => 'Salatalık Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - Adana',
        'unit' => 'kg',
        'current_price' => 19.90,
        'previous_price' => 22.90,
        'vat_rate' => 1,
        'discount_percent' => 13.1,
        'campaign_text' => 'Salata Festivali',
        'weight' => 1.0,
        'stock' => 350,
        'shelf_location' => 'B-02-01',
        'supplier_code' => 'SUP-008',
        'kunye_no' => '2070002000003',
        'description' => 'Sofralık salatalık, çıtır',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-11 11:15:00',
        'previous_price_updated_at' => '2026-01-08 16:30:00',
    ],
    [
        'sku' => 'MNV-SBZ-004',
        'barcode' => '8690002000004',
        'name' => 'Biber Dolmalık Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - Kahramanmaraş',
        'unit' => 'kg',
        'current_price' => 44.90,
        'previous_price' => 49.90,
        'vat_rate' => 1,
        'discount_percent' => 10,
        'campaign_text' => 'Dolma Günleri',
        'weight' => 1.0,
        'stock' => 100,
        'shelf_location' => 'B-03-01',
        'supplier_code' => 'SUP-009',
        'kunye_no' => '2070002000004',
        'description' => 'Dolmalık biber, et kalın',
        'production_type' => 'Geleneksel Tarım',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-10 10:30:00',
        'previous_price_updated_at' => '2026-01-07 10:00:00',
    ],
    [
        'sku' => 'MNV-SBZ-005',
        'barcode' => '8690002000005',
        'name' => 'Biber Sivri Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Çarliston',
        'origin' => 'Türkiye - Antalya',
        'unit' => 'kg',
        'current_price' => 29.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 180,
        'shelf_location' => 'B-03-02',
        'supplier_code' => 'SUP-009',
        'kunye_no' => '2070002000005',
        'description' => 'Sivri biber, tatlı',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-SBZ-006',
        'barcode' => '8690002000006',
        'name' => 'Patlıcan Kemer Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - Aydın',
        'unit' => 'kg',
        'current_price' => 34.90,
        'previous_price' => 39.90,
        'vat_rate' => 1,
        'discount_percent' => 12.5,
        'campaign_text' => 'Izgara Festivali',
        'weight' => 1.0,
        'stock' => 120,
        'shelf_location' => 'B-04-01',
        'supplier_code' => 'SUP-010',
        'kunye_no' => '2070002000006',
        'description' => 'Kemer patlıcan, ızgara için ideal',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-09 08:45:00',
        'previous_price_updated_at' => '2026-01-06 15:20:00',
    ],
    [
        'sku' => 'MNV-SBZ-007',
        'barcode' => '8690002000007',
        'name' => 'Kabak Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - Konya',
        'unit' => 'kg',
        'current_price' => 14.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 200,
        'shelf_location' => 'B-05-01',
        'supplier_code' => 'SUP-011',
        'kunye_no' => '2070002000007',
        'description' => 'Sakız kabağı, mücver için',
        'production_type' => 'Geleneksel Tarım',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-SBZ-008',
        'barcode' => '8690002000008',
        'name' => 'Patates Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Nevşehir',
        'origin' => 'Türkiye - Nevşehir',
        'unit' => 'kg',
        'current_price' => 12.90,
        'previous_price' => 14.90,
        'vat_rate' => 1,
        'discount_percent' => 13.4,
        'campaign_text' => 'Temel Gıda İndirimi',
        'weight' => 1.0,
        'stock' => 800,
        'shelf_location' => 'B-06-01',
        'supplier_code' => 'SUP-012',
        'kunye_no' => '2070002000008',
        'description' => 'Yemeklik patates',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-11 11:15:00',
        'previous_price_updated_at' => '2026-01-08 16:30:00',
    ],
    [
        'sku' => 'MNV-SBZ-009',
        'barcode' => '8690002000009',
        'name' => 'Soğan Kuru Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Tokat',
        'origin' => 'Türkiye - Tokat',
        'unit' => 'kg',
        'current_price' => 9.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 1000,
        'shelf_location' => 'B-07-01',
        'supplier_code' => 'SUP-013',
        'kunye_no' => '2070002000009',
        'description' => 'Kuru soğan, taze',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-SBZ-010',
        'barcode' => '8690002000010',
        'name' => 'Sarımsak Yerli Kg',
        'category' => 'SEBZE',
        'subcategory' => 'MANAV',
        'brand' => 'Kastamonu',
        'origin' => 'Türkiye - Kastamonu',
        'unit' => 'kg',
        'current_price' => 89.90,
        'previous_price' => 99.90,
        'vat_rate' => 1,
        'discount_percent' => 10,
        'campaign_text' => 'Sağlık Haftası',
        'weight' => 1.0,
        'stock' => 50,
        'shelf_location' => 'B-07-02',
        'supplier_code' => 'SUP-014',
        'kunye_no' => '2070002000010',
        'description' => 'Yerli sarımsak, aromatik',
        'production_type' => 'Organik',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-08 12:30:00',
        'previous_price_updated_at' => '2026-01-05 14:00:00',
    ],

    // YEŞİLLİKLER
    [
        'sku' => 'MNV-YSL-001',
        'barcode' => '8690003000001',
        'name' => 'Marul Kg',
        'category' => 'YEŞİLLİK',
        'subcategory' => 'MANAV',
        'brand' => 'Sera',
        'origin' => 'Türkiye - Antalya',
        'unit' => 'kg',
        'current_price' => 29.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 1.0,
        'stock' => 80,
        'shelf_location' => 'C-01-01',
        'supplier_code' => 'SUP-015',
        'kunye_no' => '2070003000001',
        'description' => 'Kıvırcık marul, taze',
        'production_type' => 'Konvansiyonel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-YSL-002',
        'barcode' => '8690003000002',
        'name' => 'Maydanoz Demet',
        'category' => 'YEŞİLLİK',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - İstanbul',
        'unit' => 'demet',
        'current_price' => 5.90,
        'previous_price' => 6.90,
        'vat_rate' => 1,
        'discount_percent' => 14.5,
        'campaign_text' => 'Yeşillik Günleri',
        'weight' => 0.15,
        'stock' => 200,
        'shelf_location' => 'C-02-01',
        'supplier_code' => 'SUP-016',
        'kunye_no' => '2070003000002',
        'description' => 'Taze maydanoz demeti',
        'production_type' => 'Naturel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => '2026-01-10',
    ],
    [
        'sku' => 'MNV-YSL-003',
        'barcode' => '8690003000003',
        'name' => 'Dereotu Demet',
        'category' => 'YEŞİLLİK',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - İstanbul',
        'unit' => 'demet',
        'current_price' => 5.90,
        'previous_price' => null,
        'vat_rate' => 1,
        'discount_percent' => null,
        'campaign_text' => null,
        'weight' => 0.10,
        'stock' => 150,
        'shelf_location' => 'C-02-02',
        'supplier_code' => 'SUP-016',
        'kunye_no' => '2070003000003',
        'description' => 'Taze dereotu demeti',
        'production_type' => 'Naturel',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-12 09:00:00',
        'previous_price_updated_at' => null,
    ],
    [
        'sku' => 'MNV-YSL-004',
        'barcode' => '8690003000004',
        'name' => 'Nane Demet',
        'category' => 'YEŞİLLİK',
        'subcategory' => 'MANAV',
        'brand' => 'Yerli',
        'origin' => 'Türkiye - Bursa',
        'unit' => 'demet',
        'current_price' => 6.90,
        'previous_price' => 7.90,
        'vat_rate' => 1,
        'discount_percent' => 12.7,
        'campaign_text' => 'Yeşillik Günleri',
        'weight' => 0.10,
        'stock' => 100,
        'shelf_location' => 'C-02-03',
        'supplier_code' => 'SUP-016',
        'kunye_no' => '2070003000004',
        'description' => 'Taze nane demeti',
        'production_type' => 'Organik',
        'is_featured' => 0,
        'price_updated_at' => '2026-01-11 11:15:00',
        'previous_price_updated_at' => '2026-01-09 13:45:00',
    ],
    [
        'sku' => 'MNV-YSL-005',
        'barcode' => '8690003000005',
        'name' => 'Roka Kg',
        'category' => 'YEŞİLLİK',
        'subcategory' => 'MANAV',
        'brand' => 'Organik Bahçe',
        'origin' => 'Türkiye - İzmir',
        'unit' => 'kg',
        'current_price' => 39.90,
        'previous_price' => 44.90,
        'vat_rate' => 1,
        'discount_percent' => 11.1,
        'campaign_text' => 'Organik Hafta',
        'weight' => 1.0,
        'stock' => 60,
        'shelf_location' => 'C-03-01',
        'supplier_code' => 'SUP-017',
        'kunye_no' => '2070003000005',
        'description' => 'Organik roka, baharatlı',
        'production_type' => 'Organik',
        'is_featured' => 1,
        'price_updated_at' => '2026-01-10 10:30:00',
        'previous_price_updated_at' => '2026-01-07 10:00:00',
    ],
];

// Ürünleri ekle
$inserted = 0;
$updated = 0;
$skipped = 0;

foreach ($products as $product) {
    // SKU kontrolü
    $existing = $db->fetch(
        "SELECT id FROM products WHERE company_id = ? AND sku = ?",
        [$companyId, $product['sku']]
    );

    $now = date('Y-m-d H:i:s');

    if ($existing) {
        // Güncelle
        $updateData = [
            'barcode' => $product['barcode'],
            'name' => $product['name'],
            'category' => $product['category'],
            'subcategory' => $product['subcategory'],
            'brand' => $product['brand'],
            'origin' => $product['origin'],
            'unit' => $product['unit'],
            'current_price' => $product['current_price'],
            'previous_price' => $product['previous_price'],
            'vat_rate' => $product['vat_rate'],
            'discount_percent' => $product['discount_percent'],
            'campaign_text' => $product['campaign_text'],
            'weight' => $product['weight'],
            'stock' => $product['stock'],
            'shelf_location' => $product['shelf_location'],
            'supplier_code' => $product['supplier_code'],
            'kunye_no' => $product['kunye_no'],
            'description' => $product['description'],
            'production_type' => $product['production_type'],
            'is_featured' => $product['is_featured'],
            'price_valid_until' => $product['price_valid_until'] ?? null,
            'price_updated_at' => $product['price_updated_at'] ?? null,
            'previous_price_updated_at' => $product['previous_price_updated_at'] ?? null,
            'updated_at' => $now
        ];

        $db->update('products', $updateData, 'id = ?', [$existing['id']]);
        $updated++;
        if ($isCli) echo "Güncellendi: {$product['name']}\n";
    } else {
        // Yeni ekle
        $insertData = [
            'id' => $db->generateUuid(),
            'company_id' => $companyId,
            'sku' => $product['sku'],
            'barcode' => $product['barcode'],
            'name' => $product['name'],
            'slug' => strtolower(preg_replace('/[^a-z0-9]+/i', '-', $product['name'])),
            'category' => $product['category'],
            'subcategory' => $product['subcategory'],
            'brand' => $product['brand'],
            'origin' => $product['origin'],
            'unit' => $product['unit'],
            'current_price' => $product['current_price'],
            'previous_price' => $product['previous_price'],
            'vat_rate' => $product['vat_rate'],
            'discount_percent' => $product['discount_percent'],
            'campaign_text' => $product['campaign_text'],
            'weight' => $product['weight'],
            'stock' => $product['stock'],
            'shelf_location' => $product['shelf_location'],
            'supplier_code' => $product['supplier_code'],
            'kunye_no' => $product['kunye_no'],
            'description' => $product['description'],
            'production_type' => $product['production_type'],
            'is_featured' => $product['is_featured'],
            'price_valid_until' => $product['price_valid_until'] ?? null,
            'price_updated_at' => $product['price_updated_at'] ?? null,
            'previous_price_updated_at' => $product['previous_price_updated_at'] ?? null,
            'status' => 'active',
            'created_at' => $now,
            'updated_at' => $now
        ];

        $db->insert('products', $insertData);
        $inserted++;
        if ($isCli) echo "Eklendi: {$product['name']}\n";
    }
}

if ($isCli) {
    echo "\n========================================\n";
    echo "Manav Ürünleri Seed Tamamlandı!\n";
    echo "----------------------------------------\n";
    echo "Eklenen: $inserted\n";
    echo "Güncellenen: $updated\n";
    echo "Toplam işlenen: " . count($products) . "\n";
    echo "========================================\n";
}
